### PR TITLE
Documentation: articles: LJ-article-04-2015.txt

### PR DESCRIPTION
**Pull request by jserv**
Fix indentation of the commands

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Thanks, but please follow the submission path via email as described in CONTRIBUTING.md.

**Comment by jan-kiszka** [comment]
Ping?

**Comment by jserv** [comment]
@jan-kiszka : Thanks for pointing the information about code contribution. I am about to send patches via email.

**Comment by jan-kiszka** [comment]
@jserv I still need your reply to the patch on the mailing list to actually complete this topic. Thanks.

**Pull request closed without merging**
